### ISSUE TITLE
includes to compile w/ g++ 4.4.5

### ISSUE THREAD

**Issue by brentp** [arq5x/kway-mergesort#1]
very cool implementation. i had to change the includes to get it to compile with recent g++

https://gist.github.com/812040

**Comment by arq5x** [comment]
Thanks for the help brent.  are you using that version of GCC for OpenMP?  Anyway, I hope this is of use to you, it was fun to implement.

**Comment by brentp** [comment]
i think it's the default gcc version in ubuntu 10.10. wasn't using it for openmp. i was just tinkering with it a bit
